name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        echo "REGISTRY_PERSISTENCE_DIR=${{ env.REGISTRY_PERSISTENCE_DIR }}" >> $GITHUB_ENV
        echo "REGISTRY_ID=${{ env.REGISTRY_ID }}" >> $GITHUB_ENV
        cd backend
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Install a specific version of uv.
        version: "0.7.21"
    - name: "Set up Python"
      uses: actions/setup-python@v5
    - name: Install Dependencies
      run: uv sync --locked --all-extras --dev
    - name: Run package Tests
      run: uv run pytest
    - name: Run API Tests
      run: uv run manage.py test
    - name: Clean up
      run: |
        cd ..
